---

- name: set svscan directories
  file:
    path: "{{ item.path }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
    state: directory
  loop:
    - { path: "{{ daemontools_dir }}", owner: 0, group: 0, mode: "0755" }
    - { path: "{{ daemontools_svscan_dir }}", owner: 0, group: 0, mode: "0755" }


- name: configure service on FreeBSD
  include_tasks: sysrc.yml
  vars:
    entry: "{{ daemontools_sysrc_entry }}"
  loop:
    - { name: "svscan_enable", value: "YES" }
    - { name: "svscan_servicedir", value: "{{ daemontools_svscan_dir }}" }
  loop_control:
    loop_var: daemontools_sysrc_entry
  when: ansible_system == 'FreeBSD'


- name: configure service on Linux
  block:
    - name: use custom svscanboot
      template:
        src: svscanboot
        dest: "{{ daemontools_dir }}/svscanboot"
        owner: root
        group: root
        mode: '0755'
      register: t_svscanboot

    - name: use daemontools custom service systemd script
      template:
        src: systemd/system/svscan.service
        dest: /lib/systemd/system/svscan.service
        owner: root
        group: root
      when: ansible_service_mgr == 'systemd'
      register: t_svscan

    - name: enable daemontools service
      service:
        name: "{{ daemontools_service }}"
        enabled: yes
        state: started
      register: t_service

    - name: restart daemontools service
      service:
        name: "{{ daemontools_service }}"
        state: restarted
      when: (t_svscan.changed or t_svscanboot.changed) and not t_service.changed

  when: ansible_system == 'Linux'


- name: start service
  service:
    name: "{{ daemontools_service }}"
    state: started
