---
- name: find svscan_path
  set_fact: {
    svscan_path: "{{ svscan_path | default(default_svscan_path) }}"
  }

- name: check if parent is zfs dataset
  shell: zfs list | grep '\s{{ svscan_path | dirname }}$' | cut -d ' ' -f1
  register: services_dataset
  changed_when: False

- name: create svscan_path dataset
  zfs:
    name: "{{services_dataset.stdout }}/{{ svscan_path | basename }}"
    state: present
    extra_zfs_properties:
      compression: "lz4"
  when: services_dataset.rc == 0

- name: create svscan_path directory
  file:
    path: "{{ svscan_path }}"
    state: directory
  when: services_dataset.rc != 0

- name: set svscan_path permission
  file:
    path: "{{ svscan_path }}"
    owner: root
    group: root
    mode: '0755'

- name: systemd startup script
  template:
    src: systemd/system/daemontools_svscan.service
    dest: /lib/systemd/system/daemontools_svscan.service
    owner: root
    group: root
  when: ansible_service_mgr == 'systemd'
  register: service

- name: enable daemontools svscan service
  service:
    name: daemontools_svscan
    enabled: yes
    state: started
  when: service.changed
