---
- name: set daemontools service directory
  set_fact:
    daemontools_service_dir: "{{ daemontools_service_dir | default(daemontools_default_service_dir) }}"

- name: use daemontools defaults
  block:
    - name: use daemontools default service name
      set_fact:
        daemontools_service: "{{ daemontools_default_service }}"

  when: daemontools_service_dir == daemontools_default_service_dir

- name: use daemontools custom
  block:
    - name: use daemontools custom service name
      set_fact:
        daemontools_service: "daemontools_service"

    - name: use daemontools custom service systemd script
      template:
        src: systemd/system/daemontools_service.service
        dest: /lib/systemd/system/daemontools_service.service
        owner: root
        group: root
      when: ansible_service_mgr == 'systemd'

  when: daemontools_service_dir != daemontools_default_service_dir

- name: daemontools service dir setup
  include_tasks: service_dir.yml

- name: enable daemontools svscan service
  service:
    name: "{{ daemontools_service }}"
    enabled: yes
    state: started
