---
- name: install daemontools packages
  package:
    name: '{{ item }}'
    state: 'present'
  with_flattened:
    - '{{ daemontools_packages }}'
  register: install

- name: disable default service
  service:
    name: '{{ daemontools_default_service }}'
    enabled: no
    state: stopped
  when: install.changed
