#!/bin/sh

PATH=/command:/usr/local/bin:/usr/local/sbin:/bin:/sbin:/usr/bin:/usr/sbin:/usr/X11R6/bin

exec </dev/null
exec >/dev/null
exec 2>/dev/null

svc -dx {{ daemontools_svscan_dir }}/* {{ daemontools_svscan_dir }}/*/log

env - PATH=$PATH svscan {{ daemontools_svscan_dir }} 2>&1 | \
env - PATH=$PATH readproctitle service errors: ................................................................................................................................................................................................................................................................................................................................................................................................................
